pool:
  vmImage: windows-latest
variables:
  BuildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET 5"
    inputs:
      packageType: "sdk"
      version: "5.x"

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: "**/*.csproj"
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "**/*.csproj"
      arguments: '--configuration $(BuildConfiguration) --collect "Code coverage" -s "src/test.runsettings"'
